version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    container_name: express
    command: "sleep infinity"
    depends_on:
      - redis-stack
    network_mode: service:redis-stack
  
  redis-stack:
    image: redis/redis-stack:latest
    volumes:
     - redis-data:/data
    expose:
      - 6379

volumes:
 redis-data:
 node_modules: